## 1. 资产收益率（Asset Returns）

> Source: Tsay_2010_Analysis of financial time series-3rd.pdf, Chpater 1\
> - Tsay, Ruey S. (2010). Analysis of Financial Time Series. 3rd Edition. Wiley.

大多数金融研究侧重于资产的收益率而非价格。Campbell、Lo 和 MacKinlay（1997）指出了使用收益率的两个主要原因：

1.  对于普通投资者而言，资产的收益率是一种完整且无量纲的衡量指标；
2.  相比价格序列，收益率序列具有诸多良好的统计性质，更容易分析。

然而，资产收益率的定义并不唯一，以下介绍几种常见定义（暂不考虑分红的情况）。

### 1.1 单期简单收益率（One-Period Simple Return）

若在时间点 $t - 1$ 买入一项资产并持有至时间 $t$，其\*\*简单总收益率（gross return）\*\*定义为：

$$
1 + R_t = \frac{P_t}{P_{t-1}} \quad \text{或} \quad P_t = P_{t-1}(1 + R_t)
$$

则相应的 **单期简单净收益率（net return）** 为：

$$
R_t = \frac{P_t - P_{t-1}}{P_{t-1}}
$$

### 1.2 多期简单收益率（Multiperiod Simple Return）

若持有资产 $k$ 个时期（从 $t - k$ 到 $t$），则 $k$ 期总简单收益率 为：

$$
1 + R_t^{[k]} = \frac{P_t}{P_{t-k}} = (1 + R_t)(1 + R_{t-1}) \cdots (1 + R_{t-k+1}) = \prod_{j=0}^{k-1} (1 + R_{t-j})
$$

即为单期简单收益率的乘积，又称**复利收益（compound return）**。

因此，$k$ 期净简单收益率可以采用如下公式计算：

$$
R_t^{[k]} = \frac{P_t - P_{t-k}}{P_{t-k}}
$$

在实际中，讨论收益率时需注意时间间隔（如月度、年度等）。若资产持有时间为 $k$ 年，则**年化收益率**为：

$$
\text{Annualized} \{R_t^{[k]}\} = \left( \prod_{j=0}^{k-1} (1 + R_{t-j}) \right)^{1/k} - 1
$$

这可理解为几何平均收益率，其对数形式计算为：

$$
\text{Annualized} \{R_t^{[k]}\} = \exp \left( \frac{1}{k} \sum_{j=0}^{k-1} \ln(1 + R_{t-j}) \right) - 1
$$

由于一阶泰勒展开较简单，且当 $R_t$ 较小时近似较好，因此可采用以下近似公式：

$$
\text{Annualized} \{R_t^{[k]}\} \approx \frac{1}{k} \sum_{j=0}^{k-1} R_{t-j}
$$

但在某些应用中 (部分时点上的收益率过高)，该近似的准确性可能不足。

### 1.3 连续复利收益率（Continuously Compounded Return）

在介绍连续复利收益率之前，先理解复利的影响。假设年利率为 10%，初始投资为 \$1：

-   若年付一次，则最终价值为：\$1 × (1 + 0.1) = \$1.10
-   若半年一次，单次利率为 5%，则一年后为：\$1 × (1 + 0.05)² = \$1.1025
-   若按 $m$ 次支付，则终值 (FV)：

$$
FV = 1 × \left(1 + \frac{0.1}{m} \right)^m
$$

当 $m \to \infty$ 时，终值趋近于 $\exp(0.1) = 1.10517$，即**连续复利**的结果。

因此，**连续复利终值**为：

$$
A = C \exp(r × n)
$$

其中 $C$ 为初始资金，$r$ 为年利率，$n$ 为投资年数。其对应的**现值**计算公式为：

$$
C = A \exp(-r × n)
$$

### 1.4 对数收益率（Log Return）

资产的对数收益率定义为简单收益率总额的自然对数：

$$
r_t = \ln(1 + R_t) = \ln \left(\frac{P_t}{P_{t-1}} \right) = \ln(P_t) - \ln(P_{t-1}) = p_t - p_{t-1}
$$

其中，$p_t = \ln(P_t)$。因此，**对数收益率**也称为**对数价格差（log price difference）**，通常表示为 $r_t = \Delta\ln P_t$。

> 补充说明：\
> 在实际分析中，常常对价格序列取自然对数后再进行一阶差分。对于较小的收益率，变量对数的一阶差分可以近似为该变量的百分比变化，即简单收益率：

$$
\begin{aligned}
\Delta \ln(y_t) &= \ln(y_t) - \ln(y_{t-1}) \\
&= \ln\left(\frac{y_t}{y_{t-1}}\right) \\
&= \ln(1 + R_t) \\
&\approx R_t = \frac{y_t - y_{t-1}}{y_{t-1}}
\end{aligned}
$$

其中 $R_t$ 表示 $t$ 时点的简单收益率。这里利用了 $\ln(1 + x) \approx x$ 当 $x$ 较小时的近似关系。

**对数收益率的优点**：

-   **多期总对数收益率**是各期对数收益率之和：

$$
r_t^{[k]} = r_t + r_{t-1} + \cdots + r_{t-k+1}
$$

-   **统计分析**更为方便，尤其在建模时更具可操作性。

### 1.5 投资组合收益（Portfolio Return）

若一个投资组合包含 $N$ 个资产，权重为 $w_i$，则其简单净收益为：

$$
R_{p,t} = \sum_{i=1}^{N} w_i R_{it}
$$

但对数收益率不满足线性加权性质。若 $R_{it}$ 较小，可以用近似公式：

$$
r_{p,t} \approx \sum_{i=1}^{N} w_i r_{it}
$$

### 1.6 分红影响（Dividend Payment）

若资产在 $t - 1$ 至 $t$ 期间支付红利 $D_t$，则应调整收益率计算：

$$
R_t = \frac{P_t + D_t}{P_{t-1}} - 1, \quad r_t = \ln(P_t + D_t) - \ln(P_{t-1})
$$

### 1.7 超额收益（Excess Return）

超额收益为资产收益与某一基准（如短期国债）收益之间的差值：

$$
Z_t = R_t - R_{0t}, \quad z_t = r_t - r_{0t}
$$

这是套利组合的理论回报：做多资产、做空基准，无初始投资。

> 注：“做多”即拥有该资产；“做空”指借入资产出售，并在未来买回偿还。做空者需支付红利给持有人，因此资产下跌才能盈利。

### 小结

> 对数与简单收益率关系：

$$
r_t = \ln(1 + R_t), \quad R_t = e^{r_t} - 1
$$

  若用百分数表达：

$$
r_t = 100 \ln\left(1 + \frac{R_t}{100} \right), \quad R_t = 100\left(e^{r_t / 100} - 1 \right)
$$

> 多期收益率聚合关系：

$$
1 + R_t^{[k]} = \prod_{j=0}^{k-1}(1 + R_{t-j}), \quad r_t^{[k]} = \sum_{j=0}^{k-1} r_{t-j}
$$

> 现值与终值关系（连续复利）：

$$
A = C \exp(r × n), \quad C = A \exp(-r × n)
$$